import type { WorldRegion } from '@carwars/shared';

export const midvilleRegion: WorldRegion = {
  id: 'midville',
  name: 'Midville Region',
  nodes: [
    {
      id: 'midville-city',
      name: 'Midville',
      kind: 'city',
      x: 0,
      y: 0,
      services: ['garage', 'jobs', 'market'],
    },
    {
      id: 'rustwater-truck-stop',
      name: 'Rustwater Truck Stop',
      kind: 'truck_stop',
      x: 34,
      y: -8,
      services: ['repairs', 'fuel', 'jobs'],
    },
    {
      id: 'new-boston',
      name: 'New Boston',
      kind: 'city',
      x: 76,
      y: -18,
      services: ['jobs', 'market'],
    },
    {
      id: 'fort-grimm',
      name: 'Fort Grimm',
      kind: 'arena',
      x: -18,
      y: 38,
      services: ['arena'],
      controllingGangId: 'red-jackals',
    },
    {
      id: 'dust-pike-arena',
      name: 'Dust Pike Arena',
      kind: 'arena',
      x: 46,
      y: 32,
      services: ['arena'],
    },
    {
      id: 'blacktop-market',
      name: 'Blacktop Market',
      kind: 'market',
      x: 98,
      y: 18,
      services: ['market', 'black_market'],
    },
  ],
  roads: [
    {
      id: 'midville-rustwater',
      from: 'midville-city',
      to: 'rustwater-truck-stop',
      distance: 22,
      roadType: 'highway',
      danger: 0.15,
      encounterTable: 'highway-low',
    },
    {
      id: 'rustwater-new-boston',
      from: 'rustwater-truck-stop',
      to: 'new-boston',
      distance: 31,
      roadType: 'highway',
      danger: 0.35,
      encounterTable: 'highway-medium',
    },
    {
      id: 'midville-fort-grimm',
      from: 'midville-city',
      to: 'fort-grimm',
      distance: 27,
      roadType: 'urban',
      danger: 0.65,
      encounterTable: 'gang-high',
    },
    {
      id: 'rustwater-dust-pike',
      from: 'rustwater-truck-stop',
      to: 'dust-pike-arena',
      distance: 18,
      roadType: 'dirt',
      danger: 0.4,
      encounterTable: 'dirt-medium',
    },
    {
      id: 'new-boston-blacktop',
      from: 'new-boston',
      to: 'blacktop-market',
      distance: 16,
      roadType: 'urban',
      danger: 0.3,
      encounterTable: 'urban-medium',
    },
  ],
};
